//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServcing.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BookService
    {
        public int BookingId { get; set; }

        
        [DataType(DataType.Date)]     
        [Required] 
        public Nullable<System.DateTime> Date { get; set; }


        [DataType(DataType.Time)]
        [Required]
        [Display(Name = "Start Time")]     
        public Nullable<System.TimeSpan> StartTime { get; set; }

      
        [DataType(DataType.Time)]
        [Display(Name = "End Time")]
        [Required]
       public Nullable<System.TimeSpan> EndTime { get; set; }      
        public Nullable<decimal> Amount { get; set; }

        [Display(Name = "Coupon Code")]
        public string CouponCode { get; set; }
        public Nullable<int> ServiceDetailsId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> StatusId { get; set; }

        public virtual ServiceDetail ServiceDetail { get; set; }
        public virtual Status Status { get; set; }
        public virtual UserDetail UserDetail { get; set; }
        public virtual Feedback Feedback { get; set; }
        public virtual TransactionDetail TransactionDetail { get; set; }
    }
}
