//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServcing.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Feedback
    {
        public int BookingId { get; set; }
       
        [Display(Name ="Q1 Rating")]
        public Nullable<int> Q1Rating { get; set; }

        [Display(Name = "Q2 Rating")]
        public Nullable<int> Q2Rating { get; set; }
        public string Comment { get; set; }
    
        public virtual BookService BookService { get; set; }
    }
}
