//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServcing.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ServiceDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceDetail()
        {
            this.BookServices = new HashSet<BookService>();
        }
    
        public int ServiceDetailsId { get; set; }

       [Display(Name ="Service Name")] 
       [Required]
        public string ServiceName { get; set; }

        [Required]
        public Nullable<decimal> Cost { get; set; }

        [Display(Name ="Start Time")]
        [DataType(DataType.Time)]
        [Required]
        public Nullable<System.TimeSpan> OpeningTime { get; set; }

        [Required]
        [Display(Name = "End Time")]
        [DataType(DataType.Time)]
        public Nullable<System.TimeSpan> ClosingTime { get; set; }

        [Display(Name ="Service Center")]
        [Required]
        public string ServiceCenter { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ServiceCategoryId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookService> BookServices { get; set; }
        public virtual ServiceCategory ServiceCategory { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
