//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServcing.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    
    public partial class TransactionDetail
    {
        public int BookingId { get; set; }
        public Nullable<decimal> Amount { get; set; }

        [Display(Name ="Transaction Date Time")]
        [DataType(DataType.Time)]
        public Nullable<System.DateTime> TransactionDateTime { get; set; }
    
        public virtual BookService BookService { get; set; }
    }
}
