//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServcing.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class UserDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserDetail()
        {
            this.BookServices = new HashSet<BookService>();
            this.ServiceDetails = new HashSet<ServiceDetail>();
            this.UserRoles = new HashSet<UserRole>();
        }
    
        public int Id { get; set; }

        [Required] 
        public string Email { get; set; }
       
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required]
        [Display(Name ="Confirm Password")]
        [DataType(DataType.Password)]
        [Compare("Password")]
        public string ConfirmPassword { get; set; }

       [Required]
       [Display(Name ="First Name")]
        [RegularExpression(@"^[a-zA-Z ]+[a-zA-Z]$", ErrorMessage = "First Name Format is wrong")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        [RegularExpression(@"^[a-zA-Z ]+[a-zA-Z]$", ErrorMessage = "Last Name Format is wrong")]
        public string LastName { get; set; }


       
        [Display(Name ="Contact Number")]
        [Required]
        [RegularExpression(@"^[6-9]\d{9}$", ErrorMessage = "Mobile No. Format is wrong, Write only 10 digit mobile numbers")]
        public Nullable<long> PhoneNumber { get; set; }

        [Required]
        public string Address { get; set; }

        [Display(Name ="Category Type")]
        [Required(ErrorMessage = "Category Type is Required")]
        public string UserType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookService> BookServices { get; set; }
        public virtual CouponDetail CouponDetail { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceDetail> ServiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRole> UserRoles { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
