//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServcing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public int UserId { get; set; }
        public Nullable<int> ApproverId { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string VendorStatus { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
    }
}
